import React from "react";

export default function Students() {
  return (
    <div className="container my-5">
      <h2 className="text-center fw-bold mb-4" style={{ color: "#4a274f" }}>
        🎓 Student Experience with DUBE
      </h2>

      <p className="text-muted text-center mb-5">
        DUBE makes learning personalized by adapting to your unique style — 
        whether you’re a visual, auditory, or textual learner. Here’s how you’ll use it:
      </p>

      <div className="row g-4">
        <div className="col-md-4">
          <div className="card shadow h-100 border-0">
            <div className="card-body">
              <h5 className="card-title fw-bold">1. Start Learning</h5>
              <p className="card-text">
                Access lessons provided by your teacher or generated by DUBE. 
                Materials come in multiple formats — videos, diagrams, text, and audio.
              </p>
            </div>
          </div>
        </div>

        <div className="col-md-4">
          <div className="card shadow h-100 border-0">
            <div className="card-body">
              <h5 className="card-title fw-bold">2. Personalized Adaptation</h5>
              <p className="card-text">
                After each session, take short quizzes. 
                DUBE’s AI analyzes your answers and adjusts your learning profile to fit your strengths.
              </p>
            </div>
          </div>
        </div>

        <div className="col-md-4">
          <div className="card shadow h-100 border-0">
            <div className="card-body">
              <h5 className="card-title fw-bold">3. Continuous Growth</h5>
              <p className="card-text">
                Over time, the system evolves with you. 
                Each lesson becomes more engaging, efficient, and aligned with how you learn best.
              </p>
            </div>
          </div>
        </div>
      </div>

      <p className="mt-5 text-center text-muted">
        With DUBE, studying feels natural and motivating. 
        You’ll spend less time struggling and more time mastering new knowledge. 🚀
      </p>
    </div>
  );
}
